# Setup
encoding: UTF-8
title: 개개 
description: 개발 경험이 없는 초보 개발자의 개발 일기
url: https://SeoHoiHyeong.github.io
avatar: /Profile.jpeg
paginate: 5
permalink: pretty
cover_image: /Profile.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://twitter.com/vszhub
    - https://github.com/vszhub
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Songzi Vong
  url: https://github.com/vszhub/
  email: vszhub@gmail.com
